spring:
  datasource:
    url: jdbc:mysql://reindeers-rds-instance.c3aoemok4bfc.us-west-2.rds.amazonaws.com/reindeers_db?serverTimezone=UTC
    password: reindeers
  rabbitmq:
    host: 10.1.0.33
    username: jackie
    password: 56199662
  data:
    redis:
      url: redis://:reindeers@10.1.0.33:6379
UserService:
  UserInfoUrl: http://alb.back.findthepeach.me/api/user/user-public-info/