spring:
  application:
    name: NotificationService
  datasource:
    username: root
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    port: 5672

server:
  port: 8084


