spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reindeers_db?serverTimezone=UTC
    password: ${MYSQL_PASSWORD}
  rabbitmq:
    host: localhost
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
user-service:
  url: http://localhost:8082