spring:
  datasource:
    url: jdbc:mysql://reindeers-rds-instance.c3aoemok4bfc.us-west-2.rds.amazonaws.com/reindeers_db?serverTimezone=UTC
    password: reindeers
  rabbitmq:
    host: 10.1.0.33
    username: jackie
    password: 56199662

user-service:
  url: http://alb.back.findthepeach.me