spring:
  datasource:
    url: jdbc:mysql://reindeers-rds-instance.c3aoemok4bfc.us-west-2.rds.amazonaws.com/reindeers_db?serverTimezone=UTC
    password: reindeers
  data:
    redis:
      host: redis-cluster.redis-cluster-ns.svc.cluster.local